In [ ]:
import tensorflow as tf
print(tf.__version__)

In [1]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

2024-07-09 12:46:15.907451: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# vocabulary size
voc_size=10000

One Hot Encoding

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[2058, 8877, 7148, 165], [2058, 8877, 7148, 8710], [2058, 8688, 7148, 3165], [2079, 7990, 4610, 6170, 3325], [2079, 7990, 4610, 6170, 6985], [8055, 2058, 7380, 7148, 5485], [6017, 305, 5999, 6170]]


Word Embedding Represntation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
## pre padding--making all the sentences of same length which adds 0s the front
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2058 8877 7148  165]
 [   0    0    0    0 2058 8877 7148 8710]
 [   0    0    0    0 2058 8688 7148 3165]
 [   0    0    0 2079 7990 4610 6170 3325]
 [   0    0    0 2079 7990 4610 6170 6985]
 [   0    0    0 8055 2058 7380 7148 5485]
 [   0    0    0    0 6017  305 5999 6170]]


In [11]:
## 10 feature dimesnions
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [14]:
##'the glass of milk',
embedded_docs[0]

array([   0,    0,    0,    0, 2058, 8877, 7148,  165], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 118ms/step


array([[ 0.00797558, -0.0067123 ,  0.00371362, -0.03809184,  0.00727355,
         0.03206694, -0.00324484, -0.03347186,  0.01523813,  0.02587174],
       [ 0.00797558, -0.0067123 ,  0.00371362, -0.03809184,  0.00727355,
         0.03206694, -0.00324484, -0.03347186,  0.01523813,  0.02587174],
       [ 0.00797558, -0.0067123 ,  0.00371362, -0.03809184,  0.00727355,
         0.03206694, -0.00324484, -0.03347186,  0.01523813,  0.02587174],
       [ 0.00797558, -0.0067123 ,  0.00371362, -0.03809184,  0.00727355,
         0.03206694, -0.00324484, -0.03347186,  0.01523813,  0.02587174],
       [ 0.03032147,  0.02145983,  0.03052363,  0.03251616, -0.03710002,
        -0.04743589, -0.02056797, -0.03288706, -0.0223792 , -0.01876688],
       [ 0.04529792, -0.03245987, -0.02253822,  0.01134645,  0.02076613,
        -0.04911034,  0.03057799,  0.02017634,  0.00749408, -0.04958297],
       [ 0.03715019,  0.00714087, -0.02988919,  0.03762789,  0.04023644,
        -0.03771613, -0.00691577, -0.04419313

In [17]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 29ms/step
[[[ 0.00797558 -0.0067123   0.00371362 -0.03809184  0.00727355
    0.03206694 -0.00324484 -0.03347186  0.01523813  0.02587174]
  [ 0.00797558 -0.0067123   0.00371362 -0.03809184  0.00727355
    0.03206694 -0.00324484 -0.03347186  0.01523813  0.02587174]
  [ 0.00797558 -0.0067123   0.00371362 -0.03809184  0.00727355
    0.03206694 -0.00324484 -0.03347186  0.01523813  0.02587174]
  [ 0.00797558 -0.0067123   0.00371362 -0.03809184  0.00727355
    0.03206694 -0.00324484 -0.03347186  0.01523813  0.02587174]
  [ 0.03032147  0.02145983  0.03052363  0.03251616 -0.03710002
   -0.04743589 -0.02056797 -0.03288706 -0.0223792  -0.01876688]
  [ 0.04529792 -0.03245987 -0.02253822  0.01134645  0.02076613
   -0.04911034  0.03057799  0.02017634  0.00749408 -0.04958297]
  [ 0.03715019  0.00714087 -0.02988919  0.03762789  0.04023644
   -0.03771613 -0.00691577 -0.04419313  0.00050784 -0.03455317]
  [-0.02315663  0.02359164  0.02316053  0.04629452 -0.03705